server:
  port: 8090
spring:
  application:
    name: loans
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: "qa"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "user"
#    password: "secret"

management:
  endpoints:
    web:
      exposure:
        include: "*"