spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to FurkanBank cards related QA APIs "
  contactDetails:
    name: "Furkan Yalcin - QA Lead"
    email: "furkanyalcin@furkanbank.com"
  onCallSupport:
    - (000) 111-2222
    - (000) 333-4444